# docker-compose.dev.yml - Development environment overrides
version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - APP_ENV=development
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=go_web_app
      - DB_USERNAME=root
      - DB_PASSWORD=root
    volumes:
      # Mount source code for live reload in development
      - .:/app
      # Exclude vendor and tmp from mounting to avoid conflicts
      - /app/vendor
      - /app/tmp
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    networks:
      - go-web-app-network
    command: ["air", "-c", ".air.toml"]

  mysql:
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=go_web_app
